# 1. Desafio - cap1 - trabalhando em outros contextos

Etapa 1
Projeto desafio 1: vendas online
O objetivo desse projeto é realizar uma análise dos resultados de um evento com os clientes de uma empresa de vendas online. Foi coletado um conjunto de dados que contém os clientes que mais gastaram com produtos dentro de 5 dias de vendas, que é o período de duração do evento. Essa análise vai identificar o cliente com a maior compra na semana, que irá receber um prêmio da loja, e posteriormente, ela pode ajudar a empresa a criar novas estratégias para atrair mais clientes.

Projeto desafio 2: administração de condomínios
A administração de condomínios é uma tarefa que requer muita atenção e organização. Entre as diversas responsabilidades da gestão está o recebimento dos aluguéis dos locatários. Para garantir uma boa saúde financeira do empreendimento, é fundamental que esses pagamentos sejam feitos de forma regular e pontual. No entanto, sabemos que nem sempre isso acontece.

In [1]:
import pandas as pd

In [2]:
dados_def1 = r'C:\Users\Usuario\Documents\Estudos\FIAP\Estudos\ALURA\03_Curso_Pandas_Inicial\raw\dados_vendas_clientes.json'
dados_def2 = r'C:\Users\Usuario\Documents\Estudos\FIAP\Estudos\ALURA\03_Curso_Pandas_Inicial\raw\dados_locacao_imoveis.json'

df_def1 = pd.read_json(dados_def1)
df_def2 = pd.read_json(dados_def2)

In [3]:
df_def1

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [4]:
df_def2

                                        dados_locacao
0   {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1   {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2   {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3   {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4   {'apartamento': 'C301 (blocoAP)', 'datas_combi...
5   {'apartamento': 'C302 (blocoAP)', 'datas_combi...
6   {'apartamento': 'D401 (blocoAP)', 'datas_combi...
7   {'apartamento': 'D402 (blocoAP)', 'datas_combi...
8   {'apartamento': 'E501 (blocoAP)', 'datas_combi...
9   {'apartamento': 'E502 (blocoAP)', 'datas_combi...
10  {'apartamento': 'F601 (blocoAP)', 'datas_combi...
11  {'apartamento': 'F602 (blocoAP)', 'datas_combi...
12  {'apartamento': 'G701 (blocoAP)', 'datas_combi...
13  {'apartamento': 'G702 (blocoAP)', 'datas_combi...
14  {'apartamento': 'H801 (blocoAP)', 'datas_combi...

> Normalização

In [5]:
df_def1 = pd.json_normalize(df_def1['dados_vendas'])
df_def2 = pd.json_normalize(df_def2['dados_locacao'])

In [6]:
df_def1

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [7]:
df_def2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

# 2. Exercicio a parte para prática

In [8]:
import pandas as pd
import numpy as np

# dados da firma
dados = {
    'cargo': ['Gerencia', 'Coordenação', 'Supervisão', 'Analista', 'Assistente', 'Operação', 'Auxiliar', 'Estágio', 'Assessoria', 'Consultoria'],
    'quantidade': ['2 pessoas', '1 pessoa', '3 pessoas', '4 pessoas', '5 pessoas', '3 pessoas', '2 pessoas', '1 pessoa', '1 pessoa', '1 pessoa'],
    'salario': ['$10.000 reais', '$8.000 reais', '$7.000 reais', '$5.000 reais', '$4.000 reais', '$3.500 reais', '$3.000 reais', '$1.500 reais', '$2.500 reais', '$6.000 reais']
}

# transformando o dicionário em DataFrame
df = pd.DataFrame(dados)

# df é o DataFrame com os dados da firma
df

         cargo quantidade        salario
0     Gerencia  2 pessoas  $10.000 reais
1  Coordenação   1 pessoa   $8.000 reais
2   Supervisão  3 pessoas   $7.000 reais
3     Analista  4 pessoas   $5.000 reais
4   Assistente  5 pessoas   $4.000 reais
5     Operação  3 pessoas   $3.500 reais
6     Auxiliar  2 pessoas   $3.000 reais
7      Estágio   1 pessoa   $1.500 reais
8   Assessoria   1 pessoa   $2.500 reais
9  Consultoria   1 pessoa   $6.000 reais

In [9]:
df['quantidade'] = df['quantidade'].apply(lambda x: x.replace(' pessoas', '').replace(' pessoa', '').strip())
df['salario'] = df['salario'].apply(lambda x: x.replace('$', '').replace(' reais', '').strip())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cargo       10 non-null     object
 1   quantidade  10 non-null     object
 2   salario     10 non-null     object
dtypes: object(3)
memory usage: 372.0+ bytes

In [10]:
df['salario'] = df['salario'].astype(np.float16)
df['quantidade'] = df['quantidade'].astype(np.int8)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cargo       10 non-null     object
 1   quantidade  10 non-null     int8
 2   salario     10 non-null     float16
dtypes: float16(1), int8(1), object(1)
memory usage: 242.0+ bytes

# 2. Desafio - cap2 - trabalhando em outros contextos

### 1. Desafio 1

1. Remover os dados em listas dentro do DataFrame

In [12]:
lista_colunas_def1 = list(df_def1.columns)
lista_colunas_def1 # ['Data de venda', 'Cliente', 'Valor da compra']

df_def1 = df_def1.explode(lista_colunas_def1[1:])
df_def1.reset_index(inplace=True, drop=True)
df_def1

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JOãO Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

2. Verificar os tipos de dados

In [13]:
df_def1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

3. Identificar colunas numéricas

In [14]:
df_def1['Valor da compra']

0      R$ 836,5
1     R$ 573,33
2      R$ 392,8
3     R$ 512,34
4     R$ 825,31
5     R$ 168,07
6     R$ 339,18
7     R$ 314,69
8     R$ 682,05
9     R$ 386,34
10    R$ 622,65
11    R$ 630,79
12     R$ 390,3
13    R$ 759,16
14    R$ 334,47
15    R$ 678,78
16    R$ 314,24
17    R$ 311,15
18    R$ 899,16
19    R$ 885,24
Name: Valor da compra, dtype: object

4. Transformar a coluna numérica para o tipo numérico

In [15]:
import numpy as np
df_def1['Valor da compra'] = df_def1['Valor da compra'].apply(lambda x: x.replace('R$', '').replace(',', '.').strip()).astype(np.float16)

In [16]:
df_def1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float16
dtypes: float16(1), object(2)
memory usage: 492.0+ bytes

### Desafio 2

1. Remover os dados em listas dentro do DataFrame

In [17]:
lista_colunas_def2 = list(df_def2.columns)
lista_colunas_def2 # ['apartamento','datas_combinadas_pagamento','datas_de_pagamento','valor_aluguel']

df_def2 = df_def2.explode(lista_colunas_def2[1:])
df_def2.reset_index(inplace=True, drop=True)
df_def2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
5,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
6,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
7,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
8,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
9,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
10,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
11,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
12,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
13,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
14,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
15,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
16,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
17,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
18,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
19,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
20,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
21,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
22,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
23,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
24,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
25,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
26,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
27,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
28,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
29,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

2. Verificar os tipos de dados

In [18]:
df_def2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

3. Identificar colunas numéricas

In [19]:
df_def2['valor_aluguel']

0     $ 1000,0 reais
1     $ 2500,0 reais
2     $ 1100,0 reais
3     $ 2600,0 reais
4     $ 1200,0 reais
5     $ 2700,0 reais
6     $ 1300,0 reais
7     $ 2800,0 reais
8     $ 1400,0 reais
9     $ 2900,0 reais
10    $ 1500,0 reais
11    $ 1200,0 reais
12    $ 1600,0 reais
13    $ 1300,0 reais
14    $ 1700,0 reais
15    $ 1400,0 reais
16    $ 1800,0 reais
17    $ 1500,0 reais
18    $ 1900,0 reais
19    $ 1600,0 reais
20    $ 2000,0 reais
21    $ 1000,0 reais
22    $ 2100,0 reais
23    $ 1100,0 reais
24    $ 2200,0 reais
25    $ 1200,0 reais
26    $ 2300,0 reais
27    $ 2100,0 reais
28    $ 2400,0 reais
29    $ 2200,0 reais
Name: valor_aluguel, dtype: object

4. Transformar a coluna numérica para o tipo numérico

In [20]:
df_def2['valor_aluguel'] = df_def2['valor_aluguel'].apply(lambda x: x.replace('$', '').replace(',', '.').replace(' reais', '').strip()).astype(np.float16)

In [21]:
df_def2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float16
dtypes: float16(1), object(3)
memory usage: 912.0+ bytes

# 3. Desafio - cap3 - trabalhando em outros contextos

#### 1. Devido a uma instabilidade no site da empresa, tivemos problemas com os nomes dos clientes durante o salvamento. Isso resultou em uma coluna de nomes de clientes com uma mistura de letras, maiúsculas e minúsculas, números e outros caracteres. Sabendo disso, manipule os textos presentes na coluna Cliente para que seja obtido como resultado os nomes dos clientes em letras minúsculas, com a ausência de caracteres especiais ou números.

In [27]:
df_def1['Cliente'] = df_def1['Cliente'].str.lower().replace('[^a-zA-ZÀ-ÿ\s]', '', regex=True)
df_def1

<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\Usuario\AppData\Local\Temp\ipykernel_5220\3546863723.py:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  df_def1['Cliente'] = df_def1['Cliente'].str.lower().replace('[^a-zA-ZÀ-ÿ\s]', '', regex=True)
c:\Users\Usuario\Documents\Estudos\FIAP\Estudos\.venv\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

   Data de venda          Cliente  Valor da compra
0     06/06/2022       ana lucia           836.500
1     06/06/2022  diego armandiu           573.500
2     06/06/2022  diego armandiu           392.750
3     06/06/2022  diego armandiu           512.500
4     07/06/2022  isabely joanes           825.500
5     07/06/2022  isabely joanes           168.125
6     07/06/2022  isabely joanes           339.250
7     07/06/2022  isabely joanes           314.750
8     08/06/2022  isabely joanes           682.000
9     08/06/2022    joão gabriel           386.250
10    08/06/2022  julya meireles           622.500
11    08/06/2022  julya meireles           631.000
12    09/06/2022  julya meireles           390.250
13    09/06/2022     maria julia           759.000
14    09/06/2022     maria julia           334.500
15    09/06/2022     maria julia           679.000
16    10/06/2022     maria julia           314.250
17    10/06/2022     pedro pasco           311.250
18    10/06/2022    paulo castro           899.000
19    10/06/2022   thiago fritzz           885.000

#### 2. Buscando explicar a organização da identificação dos apartamentos, durante a criação do conjunto de dados, foi adicionado o texto (blocoAP). Esse texto informa que os nomes dos apartamentos estão organizados com a letra do bloco seguida do número do apartamento. No entanto, isso não traz nenhuma informação para nossos dados, sendo interessante realizar a remoção desse texto no conjunto de dados.Com isso, manipule os textos na coluna apartamento para remover o texto (blocoAP) do DataFrame.

In [29]:
df_def2['apartamento'] = df_def2['apartamento'].str.replace(' \(blocoAP\)', '', regex=True)
df_def2

<>:1: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
<>:1: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
C:\Users\Usuario\AppData\Local\Temp\ipykernel_5220\2376698225.py:1: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
  df_def2['apartamento'] = df_def2['apartamento'].str.replace(' \(blocoAP\)', '', regex=True)
c:\Users\Usuario\Documents\Estudos\FIAP\Estudos\.venv\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0         A101                 01/06/2022         05/06/2022         1000.0
1         A101                 01/07/2022         03/07/2022         2500.0
2         A102                 02/06/2022         02/06/2022         1100.0
3         A102                 02/07/2022         06/07/2022         2600.0
4         B201                 03/06/2022         07/06/2022         1200.0
5         B201                 03/07/2022         03/07/2022         2700.0
6         B202                 04/06/2022         07/06/2022         1300.0
7         B202                 04/07/2022         05/07/2022         2800.0
8         C301                 05/06/2022         10/06/2022         1400.0
9         C301                 05/07/2022         09/07/2022         2900.0
10        C302                 06/06/2022         08/06/2022         1500.0
11        C302                 06/07/2022         12/07/2022         1200.0
12        D401                 07/06/2022         07/06/2022         1600.0
13        D401                 07/07/2022         09/07/2022         1300.0
14        D402                 08/06/2022         10/06/2022         1700.0
15        D402                 08/07/2022         14/07/2022         1400.0
16        E501                 09/06/2022         10/06/2022         1800.0
17        E501                 09/07/2022         09/07/2022         1500.0
18        E502                 10/06/2022         16/06/2022         1900.0
19        E502                 10/07/2022         12/07/2022         1600.0
20        F601                 11/06/2022         17/06/2022         2000.0
21        F601                 11/07/2022         13/07/2022         1000.0
22        F602                 12/06/2022         15/06/2022         2100.0
23        F602                 12/07/2022         12/07/2022         1100.0
24        G701                 13/06/2022         19/06/2022         2200.0
25        G701                 13/07/2022         20/07/2022         1200.0
26        G702                 14/06/2022         15/06/2022         2300.0
27        G702                 14/07/2022         17/07/2022         2100.0
28        H801                 15/06/2022         18/06/2022         2400.0
29        H801                 15/07/2022         16/07/2022         2200.0

# 5.  Desafio - cap4 - trabalhando em outros contextos

In [30]:
df_def1['Data de venda'] = pd.to_datetime(df_def1['Data de venda'])

In [38]:
df_def1_final = df_def1.groupby([df_def1['Data de venda'].dt.strftime('%m-%d'), 'Cliente'])['Valor da compra'].sum()
df_def1_final

Data de venda  Cliente
06-06          ana lucia           836.500
               diego armandiu     1478.750
07-06          isabely joanes     1647.625
08-06          isabely joanes      682.000
               joão gabriel        386.250
               julya meireles     1253.500
09-06          julya meireles      390.250
               maria julia        1772.500
10-06          maria julia         314.250
               paulo castro        899.000
               pedro pasco         311.250
               thiago fritzz       885.000
Name: Valor da compra, dtype: float32

In [ ]:
col_date = ['datas_de_pagamento', 'datas_combinadas_pagamento']
df_def2[col_date] = df_def2[col_date].map(lambda x: pd.to_datetime(x, format='%d/%m/%Y'))

In [46]:
df_def2

c:\Users\Usuario\Documents\Estudos\FIAP\Estudos\.venv\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0         A101                 2022-01-06         2022-05-06         1000.0
1         A101                 2022-01-07         2022-03-07         2500.0
2         A102                 2022-02-06         2022-02-06         1100.0
3         A102                 2022-02-07         2022-06-07         2600.0
4         B201                 2022-03-06         2022-07-06         1200.0
5         B201                 2022-03-07         2022-03-07         2700.0
6         B202                 2022-04-06         2022-07-06         1300.0
7         B202                 2022-04-07         2022-05-07         2800.0
8         C301                 2022-05-06         2022-10-06         1400.0
9         C301                 2022-05-07         2022-09-07         2900.0
10        C302                 2022-06-06         2022-08-06         1500.0
11        C302                 2022-06-07         2022-12-07         1200.0
12        D401                 2022-07-06         2022-07-06         1600.0
13        D401                 2022-07-07         2022-09-07         1300.0
14        D402                 2022-08-06         2022-10-06         1700.0
15        D402                 2022-08-07         2022-07-14         1400.0
16        E501                 2022-09-06         2022-10-06         1800.0
17        E501                 2022-09-07         2022-09-07         1500.0
18        E502                 2022-10-06         2022-06-16         1900.0
19        E502                 2022-10-07         2022-12-07         1600.0
20        F601                 2022-11-06         2022-06-17         2000.0
21        F601                 2022-11-07         2022-07-13         1000.0
22        F602                 2022-12-06         2022-06-15         2100.0
23        F602                 2022-12-07         2022-12-07         1100.0
24        G701                 2022-06-13         2022-06-19         2200.0
25        G701                 2022-07-13         2022-07-20         1200.0
26        G702                 2022-06-14         2022-06-15         2300.0
27        G702                 2022-07-14         2022-07-17         2100.0
28        H801                 2022-06-15         2022-06-18         2400.0
29        H801                 2022-07-15         2022-07-16         2200.0

In [ ]:
df_def2['atraso'] = (df_def2['datas_de_pagamento'] - df_def2['datas_combinadas_pagamento']).dt.days
df_def2_atraso = df_def2.groupby('apartamento')['atraso'].mean()

In [51]:
df_def2_atraso

apartamento
A101     89.5
A102     60.0
B201     61.0
B202     60.5
C301    138.0
C302    122.0
D401     31.0
D402     18.5
E501     15.0
E502    -25.5
F601   -129.5
F602    -87.0
G701      6.5
G702      2.0
H801      2.0
Name: atraso, dtype: float64