In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(234)
aleatorios = np.random.randint(low=950, high=1050, size=100)
df = pd.DataFrame(aleatorios, columns=['preco'])
df.head()

   preco
0   1022
1    981
2   1018
3   1007
4   1045

In [3]:
df['crescimento'] = df.preco.shift(-1).div(df.preco) - 1
df.head()

   preco  crescimento
0   1022    -0.040117
1    981     0.037717
2   1018    -0.010806
3   1007     0.037736
4   1045    -0.059330

In [4]:
df['crescimento_direto'] = df.preco.pct_change()
df.head()

   preco  crescimento  crescimento_direto
0   1022    -0.040117                 NaN
1    981     0.037717           -0.040117
2   1018    -0.010806            0.037717
3   1007     0.037736           -0.010806
4   1045    -0.059330            0.037736